### ISSUE TITLE
最新のmasterブランチを反映したバージョンをnpmに登録してほしい

### ISSUE THREAD

**Issue by TM0428** [yfakariya/review.js-vscode#19]
現在配布されているバージョンが0.19.2で[eef48edcfb3ba60ca58fcb2e535bfb3a96be64c4](https://github.com/yfakariya/review.js-vscode/tree/eef48edcfb3ba60ca58fcb2e535bfb3a96be64c4)を使用していると思いますが、現在の最新のmasterではないので、最新版を0.19.3としてReleaseしてもらえますでしょうか？

**Comment by atsushieno** [comment]
@yfakariya こちら、この関係です https://github.com/atsushieno/vscode-language-review/pull/35 お時間のあるときにお願いします〜

**Comment by yfakariya** [comment]
@TM0428 @atsushieno 

反応遅くなり申し訳ありません。

パッケージがずいぶん古くなっていたので可能な限り更新し、 `0.20.0` として公開しました！

https://www.npmjs.com/package/review.js-vscode?activeTab=readme
